### ISSUE TITLE
partition data keeps getting damaged

### ISSUE THREAD

**Issue by jangshik** [lulle2007200/SwitchSDSetup#2]
firstly thank you for your great work.
i used your script with sx os hidden partition and l4t, android premade partitions.
i setted it up with --android {path} --l4t {filepath} --no-format
and afterwards i used --fix-mbr.
first everything boots up fine(sx os partition with atmo, not with sx os)
after i connect the sd to windows(without pressing any format or anything, just cancel button)
hybrid mbr or gpt gets destroyed, turns back to msdos mbr.
could you explain why this happens? again, thnx for your amazing script.

**Comment by lulle2007200** [comment]
The --no-format option only works, when the script can find the partitions it needs, the partitions must be named correctly and large enough (e.g. first partition has to be named hos_data and must atleast be 500mb big).

As for why Windows breaks the card sometimes - that's entirely Windows fault. It either kind of works or it doesnt, that's due to the shitty way how their driver for removable media handles hybrid mbr and non Windows partitions. 
If you are really committed to get it to work in Windows, take a look at how to use the filter driver in the readme (you should know what you are doing)

**Comment by jangshik** [comment]
thanks for your reply. is the driver hitachi microdrive filter driver? i will try so after googling about it a bit. keep up the good work!
